# Generated by Django 3.0.3 on 2020-04-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='telefone_01',
            new_name='telefone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telefone_02',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=244),
        ),
    ]
