# Generated by Django 3.0.5 on 2020-04-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_auto_20200428_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='categoria',
            field=models.CharField(choices=[('Calçados', 'Calçados'), ('Roupas', 'Roupas'), ('Acessórios', 'Acessórios'), ('Outros', 'Outros')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
