# Generated by Django 3.0.5 on 2020-05-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0007_auto_20200501_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='nome_do_vendedor',
            field=models.CharField(default='', max_length=30),
        ),
    ]
