# Generated by Django 3.0.5 on 2020-05-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0008_anuncio_nome_do_vendedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='nome_do_vendedor',
            new_name='responsavel',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='preco',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='categoria',
            field=models.CharField(choices=[('Perdido', 'Perdido'), ('Adoção', 'Adoção')], max_length=10),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='cidade',
            field=models.CharField(choices=[('Vitória da Conquista-BA', 'Vitória da Conquista-BA')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
