# Generated by Django 3.0.5 on 2020-05-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0009_auto_20200511_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='idade_animal',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='nome_animal',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='sexo_animal',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Femea', 'Femea')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='categoria',
            field=models.CharField(choices=[('Desaparecido', 'Desaparecido'), ('Adoção', 'Adoção')], max_length=12),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='cidade',
            field=models.CharField(choices=[('Vitória da Conquista - BA', 'Vitória da Conquista - BA')], max_length=30),
        ),
    ]
