# Generated by Django 3.0.5 on 2020-05-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0010_auto_20200511_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='especie',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Pássaro', 'Pássaro')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='sexo_animal',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Femea', 'Femea')], default='', max_length=5),
        ),
    ]
