# Generated by Django 3.0.5 on 2020-05-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0011_auto_20200511_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='observacao',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='situacao',
            field=models.CharField(choices=[('Encontrado', 'Encontrado'), ('Adotado', 'Adotado'), ('Outro', 'Outro')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='especie',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Pássaro', 'Pássaro')], max_length=8),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='sexo_animal',
            field=models.CharField(blank=True, choices=[('Macho', 'Macho'), ('Femea', 'Femea')], max_length=5),
        ),
    ]
