# Generated by Django 3.0.5 on 2020-05-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0012_auto_20200511_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='situacao',
            field=models.CharField(blank=True, choices=[('Encontrado', 'Encontrado'), ('Adotado', 'Adotado'), ('Outro', 'Outro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
