# Generated by Django 3.0.5 on 2020-05-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0014_auto_20200512_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='raca',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='sexo_animal',
            field=models.CharField(blank=True, choices=[('Macho', 'Macho'), ('Femea', 'Femea')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='situacao',
            field=models.CharField(blank=True, choices=[('Encontrado', 'Encontrado'), ('Adotado', 'Adotado'), ('Outro', 'Outro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='titulo',
            field=models.CharField(max_length=28),
        ),
    ]
