# Generated by Django 3.0.5 on 2020-05-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0015_auto_20200512_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='faleConosco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=28)),
                ('email', models.CharField(max_length=28)),
                ('telefone', models.CharField(blank=True, default='', max_length=11)),
                ('conteudo', models.CharField(max_length=255)),
            ],
        ),
    ]
