# Generated by Django 3.0.5 on 2020-05-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0016_faleconosco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faleconosco',
            name='conteudo',
        ),
        migrations.RemoveField(
            model_name='faleconosco',
            name='telefone',
        ),
        migrations.AddField(
            model_name='faleconosco',
            name='mensagem',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
