# Generated by Django 3.0.5 on 2020-05-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0017_auto_20200512_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='observacao',
            field=models.TextField(),
        ),
    ]
